In [ ]:
#Script para gerar Tabela Funcionario

import pandas as pd
from sqlalchemy import create_engine, VARCHAR,NUMERIC,INTEGER,DATE,DATETIME,String,text,CHAR
import random
import pyodbc
from datetime import date
from faker import Faker

server = "DESKTOP-HV85ADA\\PROJETO_MERCADO"
bancodados = "MERCADO_OLTP"
driver = "ODBC Driver 17 for SQL Server"
#user = ""
#senha = ""

conexaostring = f"mssql+pyodbc://{server}/{bancodados}?driver={driver}&Trusted_Connection=yes"
#conn_str = f"mssql+pyodbc://{username}:{password}@{server}/{database}?driver={driver}"
engine = create_engine(conexaostring)

#Função para testar a conexão
def testar_conexao_sqlalchemy(engine):
    try:        
        with engine.connect() as conexao: #Tenta conectar ao banco de dados
            print("Conexão com o banco de dados estabelecida com sucesso")
            result = conexao.execute(text("SELECT 1 AS teste")) #Executa uma consulta para testar a conexão
            print("Query executada com sucesso")
            return True
    except Exception as e:
        print(f"Erro ao conectar ao banco de dados: {e}")
        return False
#testa a conexão
if testar_conexao_sqlalchemy(engine): 
    print("A conexão foi bem-sucedida")
else:
    print("Falha na conexão.")

quant_gerentes_gerados = 215

#Listas 
nomes = [
    "Maria", "Jose", "Ana", "Joao", "Antonio", "Francisco", "Carlos", "Paulo", "Pedro", "Lucas",
    "Luiz", "Marcos", "Luis", "Rafael", "Gabriel", "Daniel", "Marcelo", "Bruno", "Eduardo", "Felipe",
    "Raimundo", "Miguel", "Arthur", "Gustavo", "Leonardo", "Thiago", "Matheus", "Enzo", "Guilherme", "Davi",
    "Larissa", "Amanda", "Juliana", "Patricia", "Aline", "Camila", "Bruna", "Fernanda", "Isabela", "Mariana",
    "Tatiana", "Vanessa", "Carolina", "Bianca", "Clara", "Vitoria", "Leticia", "Laura", "Beatriz", "Julia",
    "Eliel", "Bernado", "Debora", "Shauanne", "Valdemira", "Rogeria", "Victor", "Paula", "Leandra", "Antonia",
    "Luiza", "Rafaela", "Gabriela", "Daniela", "Marcela", "Eduarda"
]

sobrenomes = [
    "Silva", "Santos", "Oliveira", "Souza", "Rodrigues", "Ferreira", "Alves", "Pereira", "Lima", "Gomes",
    "Costa", "Ribeiro", "Martins", "Carvalho", "Araujo", "Melo", "Barbosa", "Monteiro", "Cardoso", "Teixeira",
    "Mendes", "Nascimento", "Cavalcanti", "Dias", "Castro", "Campos", "Bezerra", "Fernandes", "Vieira", "Correia",
    "Sousa", "Machado", "Rocha", "Neves", "Nunes", "Moreira", "Medeiros", "Freitas", "Barros", "Pinto",
    "Andrade", "Moura", "Dantas", "Cunha", "Brito", "Leal", "Farias", "Peixoto", "Fonseca", "Azevedo"    
]

nomes_ruas = [
    "Rua Sao Joao", "Rua Santa Maria", "Rua Sao Paulo", "Rua Sao Pedro", "Rua Sao Jose",
    "Rua Sao Francisco", "Rua Santo Antonio", "Rua Sao Sebastiao", "Rua Santa Catarina",
    "Rua Luzia", "Rua Santa Rita", "Rua Santa Ana", "Rua Santa Terezinha", "Rua Santa Clara",
    "Rua Isabel", "Rua Santa Helena", "Rua Santa Cecilia", "Rua Santa Rosa", "Rua Santa Monica",
    "Rua Edwiges", "Rua Santa Ines", "Rua Santa Fe", "Rua Santa Lucia", "Rua Santa Efigenia",
    "Rua Barbara", "Rua Santa Angela", "Rua Santa Gertrudes", "Rua Santa Margarida",
    "Rua Marina", "Rua Santa Elisa", "Rua Santa Julia", "Rua Santa Zelia", "Rua Santa Zilda",
    "Rua Zulmira", "Rua Santa Zulene, Rua das Flores", "Rua da Paz", "Rua Sao Joao", "Rua Sao Paulo", "Rua Santo Antonio",
    "Rua 7 de Setembro", "Rua XV de Novembro", "Rua do Comercio", "Rua das Acacias", "Rua das Palmeiras",
    "Rua dos Cravos", "Rua do Sol", "Rua Lua Nova", "Rua da Esperanca", "Rua Sao Pedro",
    "Rua das Orquideas", "Rua das Rosas", "Rua Primavera", "Rua Santa Luzia", "Rua Sao Francisco",
    "Rua das Margaridas", "Rua do Bosque", "Rua das Aguas", "Rua Bela Vista", "Rua Santa Catarina",
    "Rua Dom Pedro I", "Rua Dom Pedro II", "Rua Marechal Deodoro", "Rua da Liberdade", "Rua do Lago",
    "Rua dos Girassois", "Rua Antonio Carlos", "Rua da Independencia", "Rua Presidente Vargas", "Rua das Laranjeiras",
    "Rua do Porto", "Rua Santos Dumont", "Rua Carlos Gomes", "Rua da Vitoria", "Rua do Carmo",
    "Rua do Campo", "Rua da Saudade", "Rua do Progresso", "Rua dos Bandeirantes", "Rua Coronel Antonio",
    "Rua Sao Jose", "Rua Benedito Calixto", "Rua dos Lirios", "Rua Sete Lagoas", "Rua Pedro Alvares Cabral",
    "Rua Castro Alves", "Rua Padre Anchieta", "Rua Machado de Assis", "Rua Monte Castelo", "Rua Humberto de Campos",
    "Rua dos Tucanos", "Rua das Violetas", "Rua do Ipe", "Rua dos Pinheiros", "Rua Jose Bonifacio",
    "Rua Getulio Vargas", "Rua Marechal Rondon", "Rua Visconde de Maua", "Rua do Horizonte", "Rua do Contorno",
    "Rua Rui Barbosa", "Rua Juscelino Kubitschek", "Rua Presidente Joao Goulart", "Rua General Osorio", "Rua dos Sonhos",
    "Rua das Figueiras", "Rua Goias", "Rua Alvorada", "Rua Bela Cintra", "Rua Piaui",
    "Rua Domingos Jorge Velho", "Rua General Carneiro", "Rua Dom Bosco", "Rua Miguel Couto", "Rua Alfredo Pujol",
    "Rua Frei Caneca", "Rua Dr. Arnaldo", "Rua Diogo Feijo", "Rua Regente Feijo", "Rua Conselheiro Lafaiete",
    "Rua Barao de Maua", "Rua Benjamin Constant", "Rua Santa Clara", "Rua Maranhao", "Rua Bahia",
    "Rua Amazonas", "Rua Acre", "Rua Sao Joaquim", "Rua dos Cedros", "Rua Tamoios",
    "Rua Jose de Alencar", "Rua Ceara", "Rua Camelia", "Rua das Cerejeiras", "Rua Japao"]

nomes_bairros = [
    "Centro", "Jardim", "Vila", "Sao Joao", "Sao Paulo", "Sao Pedro", "Sao Jose", "Sao Francisco",
    "Santo Antonio", "Sao Sebastiao", "Santa Maria", "Santa Catarina", "Santa Luzia", "Santa Rita",
    "Santa Ana", "Santa Terezinha", "Santa Clara", "Santa Isabel", "Santa Helena", "Santa Cecilia",
    "Santa Rosa", "Santa Monica", "Santa Edwiges", "Santa Ines", "Santa Fe", "Santa Lucia",
    "Santa Efigenia", "Santa Barbara", "Santa Angela", "Centro", "Jardim das Flores", "Vila Nova", "Jardim America", "Jardim Paulista",
    "Jardim Primavera", "Jardim Europa", "Jardim dos Ipes", "Jardim das Palmeiras", "Jardim Bela Vista",
    "Parque Industrial", "Jardim Alvorada", "Jardim Santa Clara", "Vila Esperanca", "Vila Maria",
    "Parque Sao Jorge", "Jardim Sao Francisco", "Jardim Santa Rita", "Vila Rica", "Vila Progresso",
    "Vila Matilde", "Vila Boa Vista", "Vila Sao Jose", "Parque dos Passaros", "Jardim Imperial",
    "Jardim Sao Luiz", "Jardim das Acacias", "Jardim Mariana", "Jardim do Lago", "Parque das Nacoes",
    "Parque dos Bandeirantes", "Jardim Atlantico", "Jardim Monte Castelo", "Jardim Eldorado", "Jardim Gloria",
    "Vila Oliveira", "Jardim Panorama", "Jardim Dom Bosco", "Vila Uniao", "Jardim Vitoria",
    "Jardim Novo Horizonte", "Vila Industrial", "Vila Augusta", "Jardim Botanico", "Jardim Sao Carlos",
    "Jardim Canada", "Jardim Santa Fe", "Jardim das Hortensias", "Parque Sao Bento", "Jardim dos Pinheiros",
    "Parque do Carmo", "Jardim Sao Joao", "Jardim Maria Helena", "Jardim Santa Rosa", "Jardim Felicidade",
    "Jardim Aurora", "Vila Santana", "Jardim Bela Vista", "Jardim das Magnolias", "Vila Medeiros",
    "Jardim dos Lirios", "Parque das Arvores", "Jardim Santa Terezinha", "Vila Nova Esperanca", "Jardim Santo Antonio",
    "Jardim Independencia", "Jardim Sao Jorge", "Jardim das Oliveiras", "Parque Estrela Dalva", "Jardim Mirante",
    "Vila Sao Pedro", "Parque Bela Vista", "Vila Nova Cachoeirinha", "Jardim Monte Alegre", "Parque Imperial",
    "Jardim Tropical", "Vila Santa Isabel", "Jardim Italia", "Jardim dos Cedros", "Jardim das Nacoes",
    "Vila Real", "Jardim dos Jacarandas", "Jardim Primavera", "Parque Paraiso", "Jardim Universo",
    "Jardim Santo Andre", "Jardim das Figueiras", "Vila Germanica", "Jardim Luz", "Vila Macedo",
    "Jardim Bonfim", "Jardim Colonial", "Jardim das Tulipas", "Vila Curuca", "Jardim Santa Maria"
]

cargos = [
'Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor',
'Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor',
'Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor',
'Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor',
'Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor','Repositor',
'Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa',
'Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa',
'Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa','Operador de caixa',
'Empacotador','Empacotador','Empacotador','Empacotador','Empacotador','Empacotador','Empacotador','Empacotador','Empacotador','Empacotador',
'Supervisor de Loja','Supervisor de Loja','Supervisor de Loja','Supervisor de Loja','Supervisor de Loja','Supervisor de Loja','Supervisor de Loja','Supervisor de Loja','Supervisor de Loja','Supervisor de Loja',
'Supervisor de Loja','Supervisor de Loja','Supervisor de Loja','Supervisor de Loja','Supervisor de Loja',
'Analista de TI','Analista de TI','Analista de TI','Analista de TI','Analista de TI',
'Analista de RH','Analista de RH','Analista de RH','Analista de RH','Analista de RH','Analista de RH','Analista de RH','Analista de RH','Analista de RH','Analista de RH',
'Analista de RH','Analista de RH','Analista de RH','Analista de RH','Analista de RH',
'Analista financeiro','Analista financeiro','Analista financeiro','Analista financeiro','Analista financeiro','Analista financeiro','Analista financeiro','Analista financeiro','Analista financeiro','Analista financeiro',
'Assistente Administrativo','Assistente Administrativo','Assistente Administrativo','Assistente Administrativo','Assistente Administrativo','Assistente Administrativo','Assistente Administrativo','Assistente Administrativo','Assistente Administrativo','Assistente Administrativo',
'Assistente Administrativo','Assistente Administrativo','Assistente Administrativo','Assistente Administrativo','Assistente Administrativo','Assistente Administrativo','Assistente Administrativo','Assistente Administrativo','Assistente Administrativo','Assistente Administrativo',
'Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque',
'Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque',
'Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque','Encarregado de estoque',
'Atendente','Atendente','Atendente','Atendente','Atendente','Atendente','Atendente','Atendente','Atendente','Atendente',
'Atendente','Atendente','Atendente','Atendente','Atendente','Atendente','Atendente','Atendente','Atendente','Atendente',
'Atendente','Atendente','Atendente','Atendente','Atendente','Atendente','Atendente','Atendente','Atendente','Atendente',
'Segurança','Segurança','Segurança','Segurança','Segurança','Segurança','Segurança','Segurança','Segurança','Segurança',
'Segurança','Segurança','Segurança','Segurança','Segurança','Segurança','Segurança','Segurança','Segurança','Segurança',
'Açougueiro','Açougueiro','Açougueiro','Açougueiro','Açougueiro','Açougueiro','Açougueiro','Açougueiro','Açougueiro','Açougueiro',
'Padeiro','Padeiro','Padeiro','Padeiro','Padeiro','Padeiro','Padeiro','Padeiro','Padeiro','Padeiro',
'Ajudante geral', 'Ajudante geral','Ajudante geral', 'Ajudante geral','Ajudante geral', 'Ajudante geral','Ajudante geral', 'Ajudante geral',
'Ajudante geral', 'Ajudante geral','Ajudante geral', 'Ajudante geral','Ajudante geral', 'Ajudante geral','Ajudante geral', 'Ajudante geral',
'Ajudante geral', 'Ajudante geral','Ajudante geral', 'Ajudante geral','Ajudante geral', 'Ajudante geral','Ajudante geral', 'Ajudante geral',
'Auxiliar de limpeza','Auxiliar de limpeza','Auxiliar de limpeza','Auxiliar de limpeza','Auxiliar de limpeza','Auxiliar de limpeza','Auxiliar de limpeza','Auxiliar de limpeza','Auxiliar de limpeza','Auxiliar de limpeza',
'Auxiliar de limpeza','Auxiliar de limpeza','Auxiliar de limpeza','Auxiliar de limpeza','Auxiliar de limpeza','Auxiliar de limpeza','Auxiliar de limpeza','Auxiliar de limpeza','Auxiliar de limpeza','Auxiliar de limpeza',
'Promotor de vendas','Promotor de vendas','Promotor de vendas','Promotor de vendas','Promotor de vendas','Promotor de vendas','Promotor de vendas','Promotor de vendas','Promotor de vendas','Promotor de vendas',
'Promotor de vendas','Promotor de vendas','Promotor de vendas','Promotor de vendas','Promotor de vendas','Promotor de vendas','Promotor de vendas','Promotor de vendas','Promotor de vendas','Promotor de vendas'
]

cargos1 = [
    'Repositor','Operador de caixa','Empacotador','Atendente','Ajudante geral','Auxiliar de limpeza']

cargos2 = [
    'Encarregado de estoque','Segurança','Padeiro','Açougueiro','Assistente Administrativo']

cargos3 = [
    'Supervisor de Loja','Promotor de vendas']

cargos4 = [
    'Analista de TI','Analista de RH','Analista financeiro']

cidades_brasil = [ 
    "Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador", "Fortaleza",
    "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Goiania",
    "Porto Alegre", "Guarulhos", "Campinas", "Sao Luis",
    "Sao Goncalo", "Maceio", "Duque de Caxias", "Natal", "Teresina",
    "Sao Bernardo do Campo", "Joao Pessoa", "Osasco",
    "Jaboatao dos Guararapes", "Ribeirao Preto", "Uberlandia", "Contagem", "Sorocaba",
    "Aracaju", "Feira de Santana", "Cuiaba", "Joinville", "Aparecida de Goiania",
    "Londrina", "Juiz de Fora", "Ananindeua", "Belford Roxo", "Niteroi",
    "Sao Joao de Meriti", "Campos dos Goytacazes", "Serra", "Caxias do Sul", "Maua",
    "Macapa", "Piracicaba", "Canoas", "Bauru", "Sao Jose dos Campos"]

df_maiores_cidades = pd.read_sql("SELECT IDCIDADE FROM CIDADE WHERE NOME IN ({})".format(','.join(f"'{cidade}'" for cidade in cidades_brasil)), engine)['IDCIDADE'].tolist()

# Função para gerar um nome completo, gênero e e-mail
def gerar_gerente():
    nome = random.choice(nomes)
    sobrenome = random.choice(sobrenomes)
    sobrenome2 = random.choice(sobrenomes)
    sobrenome3 = random.choice(sobrenomes)
    nomecompleto = f'{nome} {sobrenome} {sobrenome2} {sobrenome3}'
    id_loja = random.randint(1,150)
    id_departamento = 1
    fake = Faker() #variavel para usar Faker
    data_criacao = fake.date_time_between(start_date='-15y',end_date='-1y')
    
    return nomecompleto, id_loja, id_departamento, data_criacao

# Gerar 1000 nomes completos com gênero e e-mail
dados_nomes = [gerar_gerente() for _ in range(quant_gerentes_gerados)]
df_gerentes = pd.DataFrame(dados_nomes, columns=['NOME', 'ID_LOJA', 'ID_DEPARTAMENTO', 'DATA_CRIACAO'])

df_gerente = pd.DataFrame({

                'NOME':              df_gerentes['NOME'],
                'ID_LOJA':           df_gerentes['ID_LOJA'],
                'ID_DEPARTAMENTO':   df_gerentes['ID_DEPARTAMENTO'],
                'DATA_CRIACAO':      df_gerentes['DATA_CRIACAO'].dt.date,
                'DATA_ATLZ':         None,
                'VERSAO':            1,
})

display(df_gerente)

tipo_dados_gerente = {
                'NOME':              VARCHAR(100),
                'ID_LOJA':           INTEGER,
                'ID_DEPARTAAMENTO':  INTEGER,
                'DATA_CRIACAO':      DATE,
                'DATA_ATLZ':         DATE,
                'VERSAO':            INTEGER,
}

with engine.connect() as conn:
        conn.execute(text(f"TRUNCATE TABLE GERENTE"))  #limpa os dados existentes, pode ser removido do codigo
        conn.commit()

df_gerente.to_sql(name='GERENTE',con=engine,if_exists='append',index=False,dtype=tipo_dados_gerente)

engine.dispose()

Conexão com o banco de dados estabelecida com sucesso
Query executada com sucesso
A conexão foi bem-sucedida

,NOME,ID_LOJA,ID_DEPARTAMENTO,DATA_CRIACAO,DATA_ATLZ,VERSAO
0,Mariana Sousa Barbosa Araujo,50,1,2010-09-22,None,1
1,Francisco Nascimento Rocha Correia,108,1,2019-07-21,None,1
2,Tatiana Silva Dantas Machado,64,1,2023-07-25,None,1
3,Arthur Cunha Rocha Teixeira,13,1,2013-12-29,None,1
4,Daniela Carvalho Lima Barbosa,143,1,2018-10-02,None,1
...,...,...,...,...,...,...
495,Francisco Medeiros Campos Farias,130,1,2020-05-28,None,1
496,Beatriz Rodrigues Rodrigues Nunes,84,1,2020-11-13,None,1
497,Carolina Barros Gomes Fernandes,42,1,2011-08-02,None,1
498,Mariana Costa Teixeira Correia,108,1,2012-12-26,None,1
499,Carolina Souza Barbosa Sousa,147,1,2012-07-13,None,1

In [ ]:
#Script para gerar TABELA GERENTES A PARTIR DA FUNCIONARIOS 

import pandas as pd
from sqlalchemy import create_engine, VARCHAR,NUMERIC,INTEGER,DATE,DATETIME,String,text,CHAR
import random
import pyodbc
from datetime import date
from faker import Faker

server = "DESKTOP-HV85ADA\\PROJETO_MERCADO"
bancodados = "MERCADO_OLTP"
driver = "ODBC Driver 17 for SQL Server"
#user = ""
#senha = ""

conexaostring = f"mssql+pyodbc://{server}/{bancodados}?driver={driver}&Trusted_Connection=yes"
#conn_str = f"mssql+pyodbc://{username}:{password}@{server}/{database}?driver={driver}"
engine = create_engine(conexaostring)

#Função para testar a conexão
def testar_conexao_sqlalchemy(engine):
    try:        
        with engine.connect() as conexao: #Tenta conectar ao banco de dados
            print("Conexão com o banco de dados estabelecida com sucesso")
            result = conexao.execute(text("SELECT 1 AS teste")) #Executa uma consulta para testar a conexão
            print("Query executada com sucesso")
            return True
    except Exception as e:
        print(f"Erro ao conectar ao banco de dados: {e}")
        return False
#testa a conexão
if testar_conexao_sqlalchemy(engine): 
    print("A conexão foi bem-sucedida")
else:
    print("Falha na conexão.")

df_gerentes = pd.read_sql(text(f"SELECT * FROM FUNCIONARIO WHERE CARGO = 'Gerente' and SITUACAO = 'Ativa'"),engine)

df_gerente = pd.DataFrame({

                'NOME':              df_gerentes['NOME'],
                'ID_LOJA':           df_gerentes['ID_LOJA'],
                'ID_DEPARTAMENTO':   df_gerentes['ID_DEPARTAMENTO'],
                'DATA_CRIACAO':      df_gerentes['DATA_CRIACAO'],
                'DATA_ATLZ':         None,
                'VERSAO':            1,
})

display(df_gerente)

tipo_dados_gerente = {
                'NOME':              VARCHAR(100),
                'ID_LOJA':           INTEGER,
                'ID_DEPARTAAMENTO':  INTEGER,
                'DATA_CRIACAO':      DATE,
                'DATA_ATLZ':         DATE,
                'VERSAO':            INTEGER,
}

with engine.connect() as conn:
        conn.execute(text(f"TRUNCATE TABLE GERENTE"))  #limpa os dados existentes, pode ser removido do codigo
        conn.commit()

df_gerente.to_sql(name='GERENTE',con=engine,if_exists='append',index=False,dtype=tipo_dados_gerente)

engine.dispose()

Conexão com o banco de dados estabelecida com sucesso
Query executada com sucesso
A conexão foi bem-sucedida

,NOME,ID_LOJA,ID_DEPARTAMENTO,DATA_CRIACAO,DATA_ATLZ,VERSAO
0,Luis Castro Teixeira Carvalho,118,1,2013-07-09,None,1
1,Miguel Martins Farias Bezerra,57,1,2011-08-01,None,1
2,Ana Rodrigues Souza Carvalho,31,1,2019-01-21,None,1
3,Rafael Martins Alves Oliveira,63,1,2020-08-16,None,1
4,Vanessa Oliveira Souza Moreira,74,1,2014-04-01,None,1
5,Bianca Santos Cardoso Leal,51,1,2017-07-01,None,1
6,Marcelo Nunes Lima Fernandes,81,1,2010-12-16,None,1
7,Leticia Medeiros Cardoso Santos,123,1,2022-01-16,None,1
8,Clara Pereira Fonseca Bezerra,35,1,2015-06-05,None,1
9,Eliel Pereira Ribeiro Cardoso,110,1,2017-05-06,None,1
10,Raimundo Farias Cardoso Souza,111,1,2022-04-27,None,1
11,Camila Freitas Medeiros Moura,85,1,2016-10-26,None,1
12,Gustavo Leal Freitas Dantas,17,1,2011-04-16,None,1
13,Pedro Cunha Machado Lima,1,1,2019-01-11,None,1
14,Thiago Neves Brito Rocha,68,1,2011-08-08,None,1
15,Felipe Barbosa Peixoto Nunes,74,1,2020-11-27,None,1
16,Juliana Fernandes Rodrigues Rocha,4,1,2021-06-27,None,1
17,Vitoria Monteiro Ribeiro Medeiros,42,1,2011-08-20,None,1
18,Shauanne Brito Farias Souza,144,1,2022-12-04,None,1
19,Eduardo Araujo Ferreira Santos,32,1,2015-06-13,None,1
20,Jose Martins Campos Araujo,35,1,2012-05-26,None,1
21,Amanda Andrade Castro Rocha,39,1,2014-07-31,None,1
22,Ana Fernandes Sousa Dias,141,1,2013-01-19,None,1
23,Leonardo Azevedo Vieira Rodrigues,19,1,2011-01-18,None,1
24,Bianca Freitas Santos Barbosa,107,1,2014-02-06,None,1
25,Aline Teixeira Fonseca Pereira,81,1,2020-02-13,None,1
26,Isabela Barbosa Rocha Nascimento,146,1,2020-09-07,None,1
27,Tatiana Moreira Fernandes Leal,2,1,2021-01-02,None,1